[package]
name = "back_test"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zip = "0.5.5"
tar = "0.4.0"
flate2 = "1.0.0"
lzma-rs = "0.2.0"
async-std = "1.2.0"
